# Generated by Django 4.2.1 on 2023-05-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('supervisor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='supervisor.supervisor'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.subject'),
        ),
    ]
