# Generated by Django 4.2.1 on 2023-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
