# Generated by Django 4.2.1 on 2023-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_subject_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
