# Generated by Django 4.2.1 on 2023-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
